bfy_plugin.template_router.default_uri: '/index'
bfy_app.routing.action_name_of_404:     'controller.site:page404'
bfy_app.template_of_404:                'error/page404.html.twig'

bfy_plugin.template_router.templates_dirs:
  - dir:             '%app.dir.root%/view'
    prefix_template: 'public'

bfy_adapter.twig.template_paths:
  - '%app.dir.root%/view'

bfy_adapter.twig.configuration:
  cache: '%app.dir.root%/var/twig'
  debug: true
